### ISSUE TITLE
Clean bags Gets Error Message

### ISSUE THREAD

**Issue by nkrabben** [amiaopensource/grabbags#22]
It would be really nice to have something to get rid of all system files that might be created in existing bags, but only if they're not in a bag manifest.

**Comment by nkrabben** [comment]
Hey hey, now available in #21 

grabbags.py --clean

**Comment by jfarbowitz** [comment]
This is wonderful. I'll test before I close.

**Comment by jfarbowitz** [comment]
Hasn't been tested. Needs testing.

**Comment by jfarbowitz** [comment]
The clean function seems to start to work, but I get this error

```
Traceback (most recent call last):
  File "/Users/Jonathan/Documents/GitHub/grabbags/grabbags-dev/bin/grabbags", line 11, in <module>
    load_entry_point('grabbags', 'console_scripts', 'grabbags')()
  File "/Users/Jonathan/Documents/GitHub/grabbags/grabbags/grabbags.py", line 269, in main
    clean_bag(bag_dir)
  File "/Users/Jonathan/Documents/GitHub/grabbags/grabbags/grabbags.py", line 217, in clean_bag
    os.remove(payload_file)
FileNotFoundError: [Errno 2] No such file or directory: 'data/Thumbs.db'
```
