### ISSUE TITLE
Windows Server 2019 Install Issue?

### ISSUE THREAD

**Issue by milothiesen** [amiaopensource/grabbags#27]
Installed in Windows as per the instructions with and without a venv. Everytime I ran the script, I get this error.
```
(venv) PS C:\grabbags> grabbags C:\Users\NetX_prod_svc\Desktop\MERCH-TEST_First10images
Traceback (most recent call last):
  File "C:\grabbags\venv\Scripts\grabbags-script.py", line 11, in <module>
    load_entry_point('grabbags', 'console_scripts', 'grabbags')()
  File "C:\grabbags\venv\lib\site-packages\pkg_resources\__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\grabbags\venv\lib\site-packages\pkg_resources\__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "C:\grabbags\venv\lib\site-packages\pkg_resources\__init__.py", line 2346, in load
    return self.resolve()
  File "C:\grabbags\venv\lib\site-packages\pkg_resources\__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\grabbags\grabbags\grabbags.py", line 183
    continue
    ^
SyntaxError: 'continue' not properly in loop
```

**Comment by milothiesen** [comment]
see my pull request :)

**Comment by henryborchers** [comment]
@nkrabben is this your code or mine? I think the “continue” statements are supposed to be a “return” statement.

**Comment by henryborchers** [comment]
@mailethiesen Did some work on this. try my pull request. https://github.com/amiaopensource/grabbags/pull/29

**Comment by jfarbowitz** [comment]
@mailethiesen @henryborchers Can this issue be closed now after the pull request?

**Comment by jfarbowitz** [comment]
@milothiesen @henryborchers Is this even still an issue?

**Comment by jfarbowitz** [comment]
Haven't heard anything so closing.
