### ISSUE TITLE
Python Syntax Warning in Windows10 (within virtual python environment)

### ISSUE THREAD

**Issue by ccllaa** [amiaopensource/grabbags#34]
Command: (venv) C:\Program Files\Python\grabbags-master>grabbags --no-system-files C:\Users\User\Dropbox\HeK_Claudia\grabbag_tests\data

The data directory contains three subdirectories that I would like to bag.

Error message: 
`C:\Program Files\Python\grabbags-master\venv\Scripts\bagit.py:629: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if not manifest_filename.find("tagmanifest-") is -1:
2020-03-23 15:41:42,904 - INFO - Cleaning C:\Users\User\Dropbox\HeK_Claudia\grabbag_tests\data\S0001_001 of system files
2020-03-23 15:41:42,906 - WARNING - Removing C:\Users\User\Dropbox\HeK_Claudia\grabbag_tests\data\S0001_001\Code\.DS_Store
2020-03-23 15:41:42,907 - WARNING - Removing C:\Users\User\Dropbox\HeK_Claudia\grabbag_tests\data\S0001_001\Code\TV-BOT_2.0_code_h-ek\.DS_Store
2020-03-23 15:41:42,965 - INFO - Creating bag for directory C:\Users\User\Dropbox\HeK_Claudia\grabbag_tests\data\S0001_001
2020-03-23 15:41:42,995 - INFO - Creating data directory
2020-03-23 15:41:42,997 - INFO - Moving Code to C:\Users\User\Dropbox\HeK_Claudia\grabbag_tests\data\S0001_001\tmpg3fpd9_5\Code
2020-03-23 15:41:42,999 - ERROR - An error occurred creating a bag in C:\Users\User\Dropbox\HeK_Claudia\grabbag_tests\data\S0001_001
Traceback (most recent call last):
  File "C:\Program Files\Python\grabbags-master\venv\Scripts\bagit.py", line 224, in make_bag
    os.rename(f, new_f)
PermissionError: [WinError 5] Access is denied: 'Code' -> 'C:\\Users\\User\\Dropbox\\HeK_Claudia\\grabbag_tests\\data\\S0001_001\\tmpg3fpd9_5\\Code'
Traceback (most recent call last):
  File "C:\Program Files\Python\grabbags-master\venv\Scripts\grabbags-script.py", line 11, in <module>
    load_entry_point('grabbags', 'console_scripts', 'grabbags')()
  File "c:\program files\python\grabbags-master\grabbags\grabbags.py", line 280, in main
    make_bag(bag_dir, args)
  File "c:\program files\python\grabbags-master\grabbags\grabbags.py", line 227, in make_bag
    bag = bagit.make_bag(
  File "C:\Program Files\Python\grabbags-master\venv\Scripts\bagit.py", line 224, in make_bag
    os.rename(f, new_f)
PermissionError: [WinError 5] Access is denied: 'Code' -> 'C:\\Users\\User\\Dropbox\\HeK_Claudia\\grabbag_tests\\data\\S0001_001\\tmpg3fpd9_5\\Code'`

**Comment by jfarbowitz** [comment]
Still getting a python error in windows as of version 0.0.2. Maybe we can focus on fixing that? The other issue looks like it may be a specific permissions issue with the person's computer

```
C:\>grabbags C:\Users\farboj\Desktop\empty
c:\users\farboj\appdata\local\programs\python\python38\lib\site-packages\bagit-1.7.0-py3.8.egg\EGG-INFO\scripts\bagit.py:629: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if not manifest_filename.find("tagmanifest-") is -1:
2021-04-16 17:04:03,494 - WARNING - C:\Users\farboj\Desktop\empty\empty is an empty directory. Skipped.
2021-04-16 17:04:03,494 - INFO - 0 bags created successfully

C:\>grabbags -v
c:\users\farboj\appdata\local\programs\python\python38\lib\site-packages\bagit-1.7.0-py3.8.egg\EGG-INFO\scripts\bagit.py:629: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if not manifest_filename.find("tagmanifest-") is -1:
0.0.2
```

**Comment by jfarbowitz** [comment]
Using the same arguments, cannot reproduce the issue on my Windows 10 machine.
