### ISSUE TITLE
Bag creation is failing on hidden files

### ISSUE THREAD

**Issue by iamdamosuzuki** [amiaopensource/grabbags#65]
If the app encounters hidden files it will error out with this message. This happens even if the `--no-system-files` flag is used. 

```
Traceback (most recent call last):
  File "/usr/local/bin/grabbags", line 33, in <module>
    sys.exit(load_entry_point('grabbags==0.0.2', 'console_scripts', 'grabbags')())
  File "/usr/local/Cellar/grabbags/0.0.2/libexec/lib/python3.9/site-packages/grabbags/grabbags.py", line 372, in main
    runner(args)
  File "/usr/local/Cellar/grabbags/0.0.2/libexec/lib/python3.9/site-packages/grabbags/grabbags.py", line 295, in run
    make_bag(bag_dir, args)
  File "/usr/local/Cellar/grabbags/0.0.2/libexec/lib/python3.9/site-packages/grabbags/grabbags.py", line 259, in make_bag
    grabbags.utils.remove_system_files(root=bag_dir.path)
  File "/usr/local/Cellar/grabbags/0.0.2/libexec/lib/python3.9/site-packages/grabbags/utils.py", line 79, in remove_system_files
    os.remove(full_path)
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/SymplyUltra/Testing/TBC Presentation1/20191203_SDI/._.DS_Store'
```

**Comment by henryborchers** [comment]
@iamdamosuzuki, these are inherently difficult to recreate. Do you have some time where you could screen share your computer with me so that I can see what's going on?

**Comment by jfarbowitz** [comment]
could be that we aren't handling ```._.DS_Store``` in the script

**Comment by jfarbowitz** [comment]
I re-created a situation on my system with a ```._.DS_Store``` file and the bag seemed to be created ok and the system file was cleaned. @iamdamosuzuki Can you give us more information about your file system? It could be permissions error, I have gotten those in the past and it produced the same ```no such file``` error.
